print("So you returned home, and Japan was not hit by the atomic bomb.")
input()
print("The president was angry, but there was nothing he could do.")
input()
print("After discussion, in order to end the war as soon as possible, the United States finally chose to land in Japan and conduct a ground war.")
input()
print("However, Japan still believed that it had the strength to fight and continued to choose to fight.")
input()
print("The United States launched a large-scale battle after landing, and most of the Japanese soldiers were killed")
input()
print("The United States soon reached the vicinity of Tokyo.")
input()
print("Obviously, Japan overestimated its own strength")
input()
print("But they still refused to surrender and were ready to fight to the end")
input()
print("In the end, no amount of resistance could cover up the gap in power, and the United State soldiers captured the emperor and forces him to surredner.")
input()
print("At this point, World War II finally came to an end")