print("With your presistence, Nagasaki luckly avoided from the disaster that is about to happen.")
input()
print("So is this for the sake of the precious lives or the evil spirits getaway, the anwser would be shown with time.")
input()
print("Thousands of metres below clouds, in Tokoyo, things that are happening on the ground aren't peacefull either.")
input()
print("The power of the emperor has been significantly reduced after the bombing of Hiroshima, the first nuclear bomb dropped on Japan")
input()
print("The sound of fighting againest the emperor is rising as time passes, for the lives of the residents of Japan, the opposition must take action.")
input()
print("The angers that the residents have is like the burning flames, and will sure flood japan with the nuclear bomb on Hiroshima.")
input()
print("Not long after, a piece of new flowed here: The opposition has taken over the power of the emperor, thus the emperor had no options left but to sign the abdication edict.")
input()
print("The new goverment commited to a quick end to the war, and the unconditional surrender is signed not long after.")
input()
print("Following the surrender of Japan, the second world war came to an end.")
input()
print("Colonel name, your effort have not been wasted. The choice you made saved thousands of Japanese people's life.")